
set_property IOSTANDARD LVCMOS33 [get_ports fpga_rst]
set_property PACKAGE_PIN P20 [get_ports fpga_rst]

set_property IOSTANDARD LVCMOS33 [get_ports start_uart]
set_property PACKAGE_PIN P4 [get_ports start_uart]


set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y19} [get_ports rx]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V18} [get_ports tx]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN Y18 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_wdata[0]}]
set_property PACKAGE_PIN A21 [get_ports {io_wdata[0]}]
set_property PACKAGE_PIN E22 [get_ports {io_wdata[1]}]
set_property PACKAGE_PIN D22 [get_ports {io_wdata[2]}]
set_property PACKAGE_PIN E21 [get_ports {io_wdata[3]}]
set_property PACKAGE_PIN D21 [get_ports {io_wdata[4]}]
set_property PACKAGE_PIN G21 [get_ports {io_wdata[5]}]
set_property PACKAGE_PIN G22 [get_ports {io_wdata[6]}]
set_property PACKAGE_PIN F21 [get_ports {io_wdata[7]}]
set_property PACKAGE_PIN J17 [get_ports {io_wdata[8]}]
set_property PACKAGE_PIN L14 [get_ports {io_wdata[9]}]
set_property PACKAGE_PIN L15 [get_ports {io_wdata[10]}]
set_property PACKAGE_PIN L16 [get_ports {io_wdata[11]}]
set_property PACKAGE_PIN K16 [get_ports {io_wdata[12]}]
set_property PACKAGE_PIN M15 [get_ports {io_wdata[13]}]
set_property PACKAGE_PIN M16 [get_ports {io_wdata[14]}]
set_property PACKAGE_PIN M17 [get_ports {io_wdata[15]}]
set_property PACKAGE_PIN N19 [get_ports {io_wdata[16]}]
set_property PACKAGE_PIN N20 [get_ports {io_wdata[17]}]
set_property PACKAGE_PIN M20 [get_ports {io_wdata[18]}]
set_property PACKAGE_PIN K13 [get_ports {io_wdata[19]}]
set_property PACKAGE_PIN K14 [get_ports {io_wdata[20]}]
set_property PACKAGE_PIN M13 [get_ports {io_wdata[21]}]
set_property PACKAGE_PIN L13 [get_ports {io_wdata[22]}]
set_property PACKAGE_PIN K17 [get_ports {io_wdata[23]}]

set_property PACKAGE_PIN W4 [get_ports {io_rdata[0]}]
set_property PACKAGE_PIN R4 [get_ports {io_rdata[1]}]
set_property PACKAGE_PIN T4 [get_ports {io_rdata[2]}]
set_property PACKAGE_PIN T5 [get_ports {io_rdata[3]}]
set_property PACKAGE_PIN U5 [get_ports {io_rdata[4]}]
set_property PACKAGE_PIN W6 [get_ports {io_rdata[5]}]
set_property PACKAGE_PIN W5 [get_ports {io_rdata[6]}]
set_property PACKAGE_PIN U6 [get_ports {io_rdata[7]}]
set_property PACKAGE_PIN V5 [get_ports {io_rdata[8]}]
set_property PACKAGE_PIN R6 [get_ports {io_rdata[9]}]
set_property PACKAGE_PIN T6 [get_ports {io_rdata[10]}]
set_property PACKAGE_PIN Y6 [get_ports {io_rdata[11]}]
set_property PACKAGE_PIN AA6 [get_ports {io_rdata[12]}]
set_property PACKAGE_PIN V7 [get_ports {io_rdata[13]}]
set_property PACKAGE_PIN AB7 [get_ports {io_rdata[14]}]
set_property PACKAGE_PIN AB6 [get_ports {io_rdata[15]}]
set_property PACKAGE_PIN V9 [get_ports {io_rdata[16]}]
set_property PACKAGE_PIN V8 [get_ports {io_rdata[17]}]
set_property PACKAGE_PIN AA8 [get_ports {io_rdata[18]}]
set_property PACKAGE_PIN AB8 [get_ports {io_rdata[19]}]
set_property PACKAGE_PIN Y8 [get_ports {io_rdata[20]}]
set_property PACKAGE_PIN Y7 [get_ports {io_rdata[21]}]
set_property PACKAGE_PIN W9 [get_ports {io_rdata[22]}]
set_property PACKAGE_PIN Y9 [get_ports {io_rdata[23]}]

set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_rdata[16]}]